apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1 
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.14.2
        ports:
        - containerPort: 9200
        - containerPort: 9300
