apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: K8_Demo
    namespace: argocd
spec:
    project: default

    source:
      repoURL: https://github.com/krishna-appsec/K8POCs.git
      targetRevision: HEAD
      path: dev

    destination: 
      server: https://kubernetes.default.svc
      namespace: K8_Demo
    
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
    
      automated:
        selfHeal: true
        prune: true
