apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  selector:
    matchLabels:
      app: python
  replicas: 1 
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python:3.9.9-slim-buster
